<?xml version="1.0"?>

<robot name="link2" xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:property name="pi" value="3.1415"/>
    <xacro:property name="height" value="0.5"/>
    <xacro:property name="L2" value="0.5"/>
    <xacro:property name="L3" value="0.25"/>
    <xacro:property name="d3" value="0.5"/>


    <xacro:macro name="color">
        <material name="blue">
            <color rgba="0 0 0.8 1"/>
        </material>
    </xacro:macro>

    <xacro:macro name="link2" params="height rad">
        <visual>
            <origin xyz="${height/2} 0 0 " rpy="0 ${pi/2} 0 "/>
            <geometry>
                <cylinder radius="${rad}" length="${height}"/>
            </geometry>
            <xacro:color/>
        </visual>
        <collision>
            <origin xyz="${height/2} 0 0 " rpy="0 ${pi/2} 0 "/>
            <geometry>
                <cylinder radius="${rad}" length="${height}"/>
            </geometry>
        </collision>
        
    </xacro:macro>

    <!--Comment this out when integrating-->
    
    <!--
    <link name="base_link">
        <xacro:link2 height="0.25" rad="0.02"/>
    </link>
   
     -->
    
    
    

</robot>
