<?xml version="1.0"?>

<robot name="link1" xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:property name="pi" value="3.1415"/>
    <xacro:property name="height" value="0.5"/>
    <xacro:property name="L2" value="0.5"/>
    <xacro:property name="L3" value="0.25"/>
    <xacro:property name="d3" value="0.5"/>

    <xacro:macro name="color">
        <material name="red">
            <color rgba="1 0 0 1"/>
        </material>
    </xacro:macro>

    <xacro:macro name="default_inertial" params="mass">
        <inertial>
            <mass value="${mass}" />
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="link1" params="height rad">
        <link name = "link1">
            <visual>
                <origin xyz="0 0 ${-height/2}" rpy="0 0 0 "/>
                <geometry>
                    <cylinder radius="${rad}" length="${height}"/>
                </geometry>
                <xacro:color/>
            </visual>
            <collision>
                <origin xyz="0 0 ${height/2}" rpy="0 0 0 "/>
                <geometry>
                    <cylinder radius="${rad}" length="${height}"/>
                </geometry>
            </collision>
            <xacro:default_inertial mass="50"/>
        </link>

        <link name = "dummy1">
            <visual>
                <origin xyz="${height/2} 0 0 " rpy="0 ${pi/2} 0 "/>
                <geometry>
                    <cylinder radius="${rad}" length="${height}"/>
                </geometry>
                <xacro:color/>
            </visual>
            <collision>
                <origin xyz="0 0 ${height/2}" rpy="0 ${pi/2} 0 "/>
                <geometry>
                    <cylinder radius="${rad}" length="${height}"/>
                </geometry>
            </collision>
            <xacro:default_inertial mass="1"/>
        </link>

        <joint name="link1_fixed_joint" type="fixed">
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <parent link="link1"/>
            <child link="dummy1"/>
        </joint>
        
    </xacro:macro>

    <!--Comment this out when integrating-->
    
    <!--
    <xacro:link1 height="0.5" rad="0.02"/>
    -->    

</robot>
